# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Nurazem Kaldybaev
tagline:             Ruby, Javascript, Python, Ruby on Rails, Ember, Angular, React, Software Engineering
url:                 http://www.nurazem.com
shorturl:            nurazem.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nurazem Kaldybaev
  url:               https://twitter.com/nurazem
  email:             nurazemkg@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/nurazem/nurazem.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'

gems:
  - jekyll-redirect-from
